### ISSUE TITLE
Mobile Updates based on new design mockups

### ISSUE THREAD

**Issue by mrpritchett** [godaddy/wp-activation-theme#1]

**Comment by mrpritchett** [comment]
Mobile updated. Mobile navigation still needs a bit of work. http://liftux.wpengine.com/activation/

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;I7sCt8sM&#x2F;19-activation-fitness-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Activation (Fitness Theme)</a>

**Comment by mrpritchett** [comment]
This has been updated and pushed.
