### ISSUE TITLE
Site title missing from mobile nav

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-activation-theme#27]
<img width="332" alt="screen shot 2016-08-26 at 2 19 29 pm" src="https://cloud.githubusercontent.com/assets/522158/18017640/24646508-6b98-11e6-8c06-ec193e503c5c.png">

**Comment by chriswallace** [comment]
I'm not entirely sure how we want to approach the hidden site titles on mobile... the menu appears in front of the header in these cases and usually is positioned absolutely to ensure the menu icon is in the top right corner at all times. Will investigate ideas and report back with a solution.

**Comment by mrpritchett** [comment]
Two solutions here that I recommend at this point. 
1) Bring the title on top of the menu background when the menu is active. This could be an issue with longer site titles or large logos.
2) Move the menu down so it doesn't cover the site title or logo. This could cause some issues with scrolling and isn't honestly a great solution.

**Comment by mrpritchett** [comment]
This is now fixed.
