### ISSUE TITLE
Default install state needs to be implemented.

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-activation-theme#4]
When I install the theme, I see this:

http://lift.d.pr/ndta

Please fix the following items:
- [x] Implement color scheme from mockup as the default.
- [x] Add image from mockup to match design.
- [x] Implement additional Page Builder template called "Page Builder (No Header)" which should exclude the page title. This is used on the homepage where we don't need a page heading.

**Comment by mrpritchett** [comment]
These are now done and on GitHub on the develop branch. Please let me know what else needs to be done.

**Comment by mrpritchett** [comment]
Taking this back as I've discovered a few more issues related to this.

**Comment by mrpritchett** [comment]
There is one issue with the footer background colors that I've opend a GH issues for on Primer, otherwise I believe this to be ready to go.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;I7sCt8sM&#x2F;19-activation-fitness-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Activation (Fitness Theme)</a>

**Comment by mrpritchett** [comment]
Calling this complete.
