### ISSUE TITLE
Page Builder (No Header) Template is showing sidebar widgets

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-activation-theme#5]
These need to be removed from this particular template: http://lift.d.pr/11t3I

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;I7sCt8sM&#x2F;19-activation-fitness-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Activation (Fitness Theme)</a>

**Comment by mrpritchett** [comment]
This is done.
