### ISSUE TITLE
Mobile menu does not work

### ISSUE THREAD

**Issue by rcarthon** [godaddy/wp-activation-theme#53]
Hi, for the past couple of days I have noticed that the mobile menu for my website has not been working.

**Comment by EvanHerman** [comment]
If you can provide a link to your site we can take a look.

**Comment by rcarthon** [comment]
Sure thing.

www.richardcarthon.com

Best,
Richard Carthon
www.richardcarthon.com

**Comment by EvanHerman** [comment]
Sorry for the delay in responding @rcarthon. Are you still encountering an issue with this? In my testing of your site it appears that your menus are working.

**Comment by rcarthon** [comment]
Hi,

Yes, I was able to find a way to fix it. Thanks. 

Best,
Richard Carthon 
www.richardcarthon.com
LinkedIn Profile

**Comment by EvanHerman** [comment]
Great! I'm glad to hear that. Have a great weekend @rcarthon.

Evan
