### ISSUE TITLE
Adjust the header to look more like original design

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-activation-theme#6]
There are a few discrepancies in the implemented version:

http://lift.d.pr/1iNBO

We need to match up the title area to the design mocks.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;I7sCt8sM&#x2F;19-activation-fitness-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Activation (Fitness Theme)</a>

**Comment by mrpritchett** [comment]
This is done.
